import { jsPDF } from "jspdf";

export interface LoanReportData {
  loanName: string;
  borrowerName: string;
  currentRate: number;
  totalFacilityAmount: number;
  leverageRatio: number;
  carbonEmissions: number;
  riskScore: number;
  isCompliant: boolean;
  monthlyData: Array<{
    month: string;
    rate: number;
    leverageRatio: number;
    carbonEmissions: number;
    compliant: boolean;
  }>;
}

export function generateLoanReportPDF(data: LoanReportData): Blob {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // Header
  doc.setFontSize(20);
  doc.setTextColor(16, 185, 129); // Emerald color
  doc.text("Covenant360 Loan Report", pageWidth / 2, yPosition, { align: "center" });
  yPosition += 10;

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Loan: ${data.loanName}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Borrower: ${data.borrowerName}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, yPosition);
  yPosition += 15;

  // Current Status
  doc.setFontSize(16);
  doc.text("Current Status", 20, yPosition);
  yPosition += 10;

  doc.setFontSize(11);
  doc.text(`Interest Rate: ${data.currentRate.toFixed(2)}%`, 20, yPosition);
  yPosition += 7;
  doc.text(`Risk Score: ${data.riskScore.toFixed(1)}/100`, 20, yPosition);
  yPosition += 7;
  doc.text(`Leverage Ratio: ${data.leverageRatio.toFixed(2)}x`, 20, yPosition);
  yPosition += 7;
  doc.text(`Carbon Emissions: ${data.carbonEmissions} tons`, 20, yPosition);
  yPosition += 7;
  doc.text(
    `Compliance Status: ${data.isCompliant ? "COMPLIANT" : "NON-COMPLIANT"}`,
    20,
    yPosition
  );
  yPosition += 15;

  // Historical Data Table
  if (data.monthlyData.length > 0) {
    doc.setFontSize(16);
    doc.text("Historical Performance", 20, yPosition);
    yPosition += 10;

    // Table header
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Month", 20, yPosition);
    doc.text("Rate", 60, yPosition);
    doc.text("Leverage", 90, yPosition);
    doc.text("Carbon", 130, yPosition);
    doc.text("Status", 160, yPosition);
    yPosition += 7;

    doc.setFont("helvetica", "normal");
    data.monthlyData.forEach((month) => {
      if (yPosition > pageHeight - 20) {
        doc.addPage();
        yPosition = 20;
      }

      doc.text(month.month, 20, yPosition);
      doc.text(`${month.rate.toFixed(2)}%`, 60, yPosition);
      doc.text(`${month.leverageRatio.toFixed(2)}x`, 90, yPosition);
      doc.text(`${month.carbonEmissions}`, 130, yPosition);
      doc.text(month.compliant ? "OK" : "BREACH", 160, yPosition);
      yPosition += 7;
    });
  }

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
    doc.text(
      "Generated by Covenant360 - The Operating System for Sustainability-Linked Loans",
      pageWidth / 2,
      pageHeight - 5,
      { align: "center" }
    );
  }

  return doc.output("blob");
}

